name: CI/CD Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3️⃣ Install dependencies for testing (includes dev dependencies)
    - name: Install dependencies
      run: npm ci

    # 4️⃣ Run tests
    - name: Run tests
      run: npm test

    # 5️⃣ Deploy to EC2 via SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
       host: ${{ secrets.EC2_HOST }}
       username: ubuntu
       key: ${{ secrets.EC2_SSH_KEY }}
       env:
         BRANCH: ${{ github.ref_name }}
      script: |
        set -e
        echo "Deploying branch: $BRANCH"

        if [ "$BRANCH" = "dev" ]; then
          APP_DIR="/var/www/nodeapp-dev"
          PM2_NAME="nodeapp-dev"
        else
          APP_DIR="/var/www/nodeapp-prod"
          PM2_NAME="nodeapp-prod"
        fi

        cd $APP_DIR
        git fetch origin
        git reset --hard origin/$BRANCH
        git clean -fd
        npm ci --omit=dev
        pm2 restart $PM2_NAME || pm2 start app/index.js --name $PM2_NAME
        pm2 save
        pm2 flush
        git log -1 --oneline